export interface UsMarketItem {
  rank: number;
  city: string;
  metroArea: string;
  state: string;
  notes: string;
}

export const US_TOP_50_MARKETS: UsMarketItem[] = [
  { rank: 1, city: 'New York', metroArea: 'New York-Newark-Jersey City, NY-NJ-PA', state: 'NY', notes: 'World capital for theater and live music; TKTS offers same-day half-price Broadway tickets; The Skint for budget culture.' },
  { rank: 2, city: 'Los Angeles', metroArea: 'Los Angeles-Long Beach-Anaheim, CA', state: 'CA', notes: 'Heavy concentration of AXS/AEG venues; Curate LA for visual art; Hollywood Bowl direct box office.' },
  { rank: 3, city: 'Chicago', metroArea: 'Chicago-Naperville-Elgin, IL-IN-WI', state: 'IL', notes: 'Birthplace of Tock and Metromix; Hot Tix discount theater across 200+ companies; Do312 & Metro.' },
  { rank: 4, city: 'Dallas', metroArea: 'Dallas-Fort Worth-Arlington, TX', state: 'TX', notes: 'AT&T PAC, Bass Performance Hall, Deep Ellum live music hub anchored by AXS and Eventbrite.' },
  { rank: 5, city: 'Houston', metroArea: 'Houston-The Woodlands-Sugar Land, TX', state: 'TX', notes: 'Downtown 17-block Theater District; Miller Outdoor Theatre free reserved seats; White Oak Music Hall.' },
  { rank: 6, city: 'Washington', metroArea: 'Washington-Arlington-Alexandria, DC-VA-MD-WV', state: 'DC', notes: '730 DC and Clockout DC; I.M.P. runs legendary 9:30 Club, The Anthem, and Lincoln Theatre.' },
  { rank: 7, city: 'Philadelphia', metroArea: 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD', state: 'PA', notes: 'Ensemble Arts Philly unifies Kimmel Campus; Uwishunu official Visit Philly weekly event breakdown.' },
  { rank: 8, city: 'Miami', metroArea: 'Miami-Fort Lauderdale-Pompano Beach, FL', state: 'FL', notes: 'Miami Spice dining; DICE dominant for Wynwood/downtown nightlife; Adrienne Arsht Center.' },
  { rank: 9, city: 'Atlanta', metroArea: 'Atlanta-Sandy Springs-Alpharetta, GA', state: 'GA', notes: 'Woodruff Arts Center, Fox Theatre, Freshtix regional engine, and Atlanta Parent.' },
  { rank: 10, city: 'Boston', metroArea: 'Boston-Cambridge-Newton, MA-NH', state: 'MA', notes: 'ArtsBoston / BosTix discount theater; The Boston Calendar crowdsourced grassroots guide.' },
  { rank: 11, city: 'Phoenix', metroArea: 'Phoenix-Mesa-Chandler, AZ', state: 'AZ', notes: 'Stateside Presents indie concerts; Herberger Theater; Cactus League spring training.' },
  { rank: 12, city: 'San Francisco', metroArea: 'San Francisco-Oakland-Berkeley, CA', state: 'CA', notes: 'Funcheap SF budget guide; Another Planet Entertainment (Outside Lands); BroadwaySF.' },
  { rank: 13, city: 'Riverside', metroArea: 'Riverside-San Bernardino-Ontario, CA', state: 'CA', notes: 'Toyota Arena on AXS; Glen Helen Amphitheater largest outdoor amphitheater in US.' },
  { rank: 14, city: 'Detroit', metroArea: 'Detroit-Warren-Dearborn, MI', state: 'MI', notes: '313 Presents unifies Fox Theatre & LCA; Movement Electronic Music Festival.' },
  { rank: 15, city: 'Seattle', metroArea: 'Seattle-Tacoma-Bellevue, WA', state: 'WA', notes: 'EverOut Seattle / Stranger Tickets indie arts; Seattle Theatre Group (Paramount, Moore, Neptune).' },
  { rank: 16, city: 'Minneapolis', metroArea: 'Minneapolis-St. Paul-Bloomington, MN-WI', state: 'MN', notes: 'First Avenue & 7th St Entry indie ecosystem on AXS; Racket MN alt-media; Guthrie Theater.' },
  { rank: 17, city: 'San Diego', metroArea: 'San Diego-Chula Vista-Carlsbad, CA', state: 'CA', notes: 'Belly Up Tavern, Casbah; La Jolla Playhouse & Old Globe Tony-winning launchpads.' },
  { rank: 18, city: 'Tampa', metroArea: 'Tampa-St. Petersburg-Clearwater, FL', state: 'FL', notes: 'Straz Center 2nd largest PAC in Southeast; Jannus Live historic outdoor music venue.' },
  { rank: 19, city: 'Denver', metroArea: 'Denver-Aurora-Lakewood, CO', state: 'CO', notes: 'Red Rocks Amphitheatre & Mission Ballroom on AXS; Denver Center for the Performing Arts.' },
  { rank: 20, city: 'Baltimore', metroArea: 'Baltimore-Columbia-Towson, MD', state: 'MD', notes: 'Merriweather Post Pavilion (I.M.P.); Hippodrome Theatre; Ottobar punk/indie landmark.' },
  { rank: 21, city: 'St. Louis', metroArea: 'St. Louis, MO-IL', state: 'MO', notes: 'MetroTix independent regional ticketing agency for 40+ institutions; The Muny Forest Park.' },
  { rank: 22, city: 'Orlando', metroArea: 'Orlando-Kissimmee-Sanford, FL', state: 'FL', notes: 'Bungalower downtown neighborhood aggregator; Dr. Phillips Center; Orlando Fringe.' },
  { rank: 23, city: 'Charlotte', metroArea: 'Charlotte-Concord-Gastonia, NC-SC', state: 'NC', notes: 'Blumenthal Arts centralized uptown ticketing; Queen City Nerve cultural journalism.' },
  { rank: 24, city: 'San Antonio', metroArea: 'San Antonio-New Braunfels, TX', state: 'TX', notes: 'Historic Majestic Theatre Broadway via ATG; Tobin Center civic performing arts ticketing.' },
  { rank: 25, city: 'Portland', metroArea: 'Portland-Vancouver-Hillsboro, OR-WA', state: 'OR', notes: 'Portland 5 Centers for the Arts; EverOut Portland; McMenamins historic music circuit.' },
  { rank: 26, city: 'Sacramento', metroArea: 'Sacramento-Roseville-Folsom, CA', state: 'CA', notes: 'Sacramento 365 community arts aggregator; Broadway Sacramento; SAFE Credit Union PAC.' },
  { rank: 27, city: 'Pittsburgh', metroArea: 'Pittsburgh, PA', state: 'PA', notes: 'Pittsburgh Cultural Trust 14-block Cultural District; ShowClix founding home.' },
  { rank: 28, city: 'Austin', metroArea: 'Austin-Round Rock-Georgetown, TX', state: 'TX', notes: 'Do512 HQ; Prekindle indie venue ticketing; Austin City Limits & SXSW ecosystem.' },
  { rank: 29, city: 'Las Vegas', metroArea: 'Las Vegas-Henderson-Paradise, NV', state: 'NV', notes: 'The Smith Center non-gaming cultural hub; Vegas.com ticketing engine; Strip residencies.' },
  { rank: 30, city: 'Cincinnati', metroArea: 'Cincinnati, OH-KY-IN', state: 'OH', notes: 'Cincinnati Arts Association centralizes historic Music Hall and Aronoff Center.' },
  { rank: 31, city: 'Kansas City', metroArea: 'Kansas City, MO-KS', state: 'MO', notes: 'Kauffman Center box office; Starlight Theatre historic 7,900-seat outdoor amphitheater.' },
  { rank: 32, city: 'Columbus', metroArea: 'Columbus, OH', state: 'OH', notes: 'CAPA historic theatre management; PromoWest / KEMBA Live! on AXS.' },
  { rank: 33, city: 'Indianapolis', metroArea: 'Indianapolis-Carmel-Anderson, IN', state: 'IN', notes: 'Do317 live entertainment platform; The Palladium at Carmel; IRT theatre.' },
  { rank: 34, city: 'Cleveland', metroArea: 'Cleveland-Elyria, OH', state: 'OH', notes: 'Playhouse Square largest PAC outside Lincoln Center; Severance Music Center.' },
  { rank: 35, city: 'San Jose', metroArea: 'San Jose-Sunnyvale-Santa Clara, CA', state: 'CA', notes: 'Team San Jose municipal box office across California Theatre & San Jose Civic.' },
  { rank: 36, city: 'Nashville', metroArea: 'Nashville-Davidson-Murfreesboro-Franklin, TN', state: 'TN', notes: 'NowPlayingNashville non-profit portal; Ryman Auditorium & Grand Ole Opry on AXS.' },
  { rank: 37, city: 'Virginia Beach', metroArea: 'Virginia Beach-Norfolk-Newport News, VA-NC', state: 'VA', notes: 'SevenVenues Norfolk municipal ticketing; Sandler Center for Performing Arts.' },
  { rank: 38, city: 'Providence', metroArea: 'Providence-Warwick, RI-MA', state: 'RI', notes: 'WaterFire signature civic event; Providence Performing Arts Center (PPAC); Motif.' },
  { rank: 39, city: 'Jacksonville', metroArea: 'Jacksonville, FL', state: 'FL', notes: 'FSCJ Artist Series Broadway tours; historic Florida Theatre non-profit box office.' },
  { rank: 40, city: 'Milwaukee', metroArea: 'Milwaukee-Waukesha, WI', state: 'WI', notes: 'Summerfest music festival; Marcus Performing Arts Center; Milwaukee365 arts board.' },
  { rank: 41, city: 'Oklahoma City', metroArea: 'Oklahoma City, OK', state: 'OK', notes: 'Civic Center Music Hall direct box office; Tower Theatre & Beer City Music Hall.' },
  { rank: 42, city: 'Raleigh', metroArea: 'Raleigh-Cary, NC', state: 'NC', notes: 'DPAC in Durham top 5 US theater attendance; Martin Marietta Center; INDY Week.' },
  { rank: 43, city: 'Memphis', metroArea: 'Memphis, TN-MS-AR', state: 'TN', notes: 'Choose901 civic storytelling platform; Orpheum Theatre Group; Beale Street clubs.' },
  { rank: 44, city: 'Richmond', metroArea: 'Richmond, VA', state: 'VA', notes: 'eTix powerhouse market (Altria Theater, Dominion Energy Center, The National).' },
  { rank: 45, city: 'Louisville', metroArea: 'Louisville/Jefferson County, KY-IN', state: 'KY', notes: 'Kentucky Performing Arts statewide ticketing; Kentucky Derby Festival; Do502.' },
  { rank: 46, city: 'New Orleans', metroArea: 'New Orleans-Metairie, LA', state: 'LA', notes: 'WWOZ Livewire definitive music calendar; Saenger Theatre Broadway; Tipitinas.' },
  { rank: 47, city: 'Salt Lake City', metroArea: 'Salt Lake City, UT', state: 'UT', notes: 'ArtTix county-wide ticketing; 24tix local venue platform (Kilby Court, Urban Lounge).' },
  { rank: 48, city: 'Hartford', metroArea: 'Hartford-East Hartford-Middletown, CT', state: 'CT', notes: 'The Bushnell Center cultural engine; Hartford Stage Tony-winning regional theater.' },
  { rank: 49, city: 'Buffalo', metroArea: 'Buffalo-Cheektowaga, NY', state: 'NY', notes: 'Step Out Buffalo community guide; Sheas 1926 historic Broadway palace.' },
  { rank: 50, city: 'Birmingham', metroArea: 'Birmingham-Hoover, AL', state: 'AL', notes: 'Bham Now digital event guide; BJCC Concert Hall centerpiece complex.' },
];
