export const mockEvents = [
  {
    id: 'e1',
    title: 'Vanguard Social Dinner',
    description: 'Exclusive evening of curated networking at The Glass House Rooftop.',
    type: 'JOINED CIRCLE',
    category: 'Dining',
    image: '/vanguard_social_1774367422848.png',
    timeLabel: '7:30 PM Today',
    date: 'Today',
    time: '7:30 PM',
    distance: '0.8 MI AWAY',
    location: 'The Glass House Rooftop',
    capacity: 75,
    maxSpots: 50,
    status: 'Attending',
    avatars: ['Felix', 'Aneka', 'Jocelyn'],
    confirmed: 48,
    maybe: 15,
    interested: 102,
    waitlist: 3,
    vibe: "Exclusive evening of curated networking at The Glass House Rooftop. Join us for a night of meaningful connections and high-end dining."
  },
  {
    id: 'e2',
    title: 'Morning Ridge Trail',
    description: 'Medium-intensity 5k hike followed by breakfast at the trailhead cafe.',
    type: 'PUBLIC EVENT',
    category: 'Active',
    image: '/morning_ridge_1774367438744.png',
    timeLabel: 'Sat, 9:00 AM',
    date: 'Sat, Oct 25',
    time: '9:00 AM',
    distance: '4.2 MI AWAY',
    location: 'Morning Ridge Trailhead',
    capacity: 10,
    maxSpots: 20,
    status: 'RSVP Now',
    avatars: [],
    confirmed: 8,
    maybe: 4,
    interested: 45,
    waitlist: 0,
    vibe: "Start your weekend with fresh air and great company. We'll hit the ridge trail for a 5k loop then grab coffee and pastries at the base."
  },
  {
    id: 'e3',
    title: 'Underground Vinyl Set',
    description: 'A curated selection of rare soul and jazz imports in a cozy basement setting.',
    type: 'JAZZ COLLECTIVE',
    category: 'Entertainment',
    image: '/vinyl_set_1774367456136.png',
    timeLabel: 'Tomorrow, 9:00 PM',
    date: 'Tomorrow',
    time: '9:00 PM',
    distance: '1.5 MI AWAY',
    location: 'The Basement Studio',
    capacity: 95,
    maxSpots: 40,
    status: 'Pending RSVP',
    fillingFast: true,
    avatars: [],
    confirmed: 35,
    maybe: 12,
    interested: 88,
    waitlist: 0,
    vibe: "Strictly vinyl. Strictly soul. Join us for an intimate listening session featuring rare imports and guest selectors."
  }
];
